---

- set_fact:
    cpd_current_dir: "{{ cpd_project_web_dir }}/current"
    cpd_release_dir: "{{ cpd_project_web_dir }}/releases"

- name: Create missing directories.
  file:
    state: directory
    path: "{{ cpd_release_dir }}"
  become: true
  become_user: "{{ cpd_www_user }}"

- name: Synchronize release.
  synchronize:
    src: "{{ cpd_current_workspace }}"
    dest: "{{ cpd_release_dir }}"

- name: Run composer install remote.
  command: "composer install {{ cpd_install_options_remote }}"
  args:
    chdir: "{{ cpd_release_dir }}/{{ cpd_release_name }}"

- name: Set permissions.
  file:
    path: "{{ cpd_release_dir }}/{{ cpd_release_name }}"
    owner: "{{ cpd_www_user }}"
    group: "{{ cpd_www_user }}"
    state: directory
    recurse: true
